import type { Config } from 'tailwindcss'

export default {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                   '#f3ffca',
        'primary-container':         '#cafd00',
        'primary-fixed':             '#cafd00',
        'primary-fixed-dim':         '#beee00',
        'primary-dim':               '#beee00',
        'on-primary':                '#516700',
        'on-primary-container':      '#4a5e00',
        'on-primary-fixed':          '#3a4a00',
        'on-primary-fixed-variant':  '#526900',
        'secondary':                 '#ff6e85',
        'secondary-dim':             '#e31754',
        'secondary-container':       '#bd0042',
        'secondary-fixed':           '#ffc2c8',
        'secondary-fixed-dim':       '#ffaeb7',
        'on-secondary':              '#480014',
        'on-secondary-container':    '#fff6f5',
        'on-secondary-fixed':        '#6e0023',
        'on-secondary-fixed-variant':'#a30038',
        'tertiary':                  '#fbf8fc',
        'tertiary-dim':              '#edeaee',
        'tertiary-container':        '#edeaee',
        'tertiary-fixed':            '#fefbff',
        'tertiary-fixed-dim':        '#f0edf1',
        'on-tertiary':               '#5f5e62',
        'on-tertiary-container':     '#57565a',
        'on-tertiary-fixed':         '#4f4e51',
        'on-tertiary-fixed-variant': '#6c6b6e',
        'background':                '#0e0e10',
        'surface':                   '#0e0e10',
        'surface-dim':               '#0e0e10',
        'surface-bright':            '#2c2c2f',
        'surface-variant':           '#262528',
        'surface-container-lowest':  '#000000',
        'surface-container-low':     '#131315',
        'surface-container':         '#19191c',
        'surface-container-high':    '#1f1f22',
        'surface-container-highest': '#262528',
        'surface-tint':              '#f3ffca',
        'on-background':             '#f9f5f8',
        'on-surface':                '#f9f5f8',
        'on-surface-variant':        '#adaaad',
        'inverse-surface':           '#fcf8fb',
        'inverse-on-surface':        '#565457',
        'inverse-primary':           '#516700',
        'outline':                   '#767577',
        'outline-variant':           '#48474a',
        'error':                     '#ff7351',
        'error-dim':                 '#d53d18',
        'error-container':           '#b92902',
        'on-error':                  '#450900',
        'on-error-container':        '#ffd2c8',
      },
      fontFamily: {
        'headline': ['"Space Grotesk"', 'sans-serif'],
        'body':     ['"Inter"',         'sans-serif'],
        'label':    ['"Space Grotesk"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        sm:  '0px',
        md:  '0px',
        lg:  '0px',
        xl:  '0px',
        '2xl': '0px',
        full: '9999px',
      },
    },
  },
  plugins: [],
} satisfies Config
